// import { Montserrat } from 'next/font/google'
// import type { Metadata } from 'next'
// import './globals.css'

// const montserrat = Montserrat({
//   weight: '400',
//   subsets: ['latin'],
// })

// export const metadata: Metadata = {
//   title: 'Test NextJS',
//   description: 'Generated by create next app',
// }
 
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en" className={montserrat.className}>
//       <body>{children}</body>
//     </html>
//   )
// }

// ใช้ TanStack Query เพิ่มด้วย
// /app/layout.tsx
'use client'

import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactNode } from 'react'
import './globals.css' // ถ้ามี CSS ทั่วไป

// สร้าง QueryClient ครั้งเดียว
const queryClient = new QueryClient()

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  )
}